# Generated by Django 5.0.2 on 2024-02-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0003_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
