# Generated by Django 5.0.2 on 2024-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0003_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
