# Generated by Django 5.0.2 on 2024-02-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0006_alter_fakepayment_email_alter_fakepayment_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakepayment',
            name='description',
        ),
    ]
