# Generated by Django 5.0.2 on 2024-02-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0006_alter_fakepayment_email_alter_fakepayment_last_name_and_more'),
        ('techwave', '0006_alter_product_category'),
    ]

    operations = [
    ]
