# Generated by Django 5.0.2 on 2024-02-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0007_remove_fakepayment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakepayment',
            name='amount',
        ),
    ]
