# Generated by Django 5.0.2 on 2024-02-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0007_merge_20240223_1459'),
        ('techwave', '0010_remove_order_is_paid_order_quantity_and_more'),
    ]

    operations = [
    ]
