# Generated by Django 5.0.2 on 2024-02-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0010_remove_order_is_paid_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
    ]
