# Generated by Django 5.0.2 on 2024-02-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0011_alter_order_options_remove_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
