# Generated by Django 5.0.2 on 2024-02-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0007_merge_20240223_1459'),
        ('techwave', '0013_remove_order_image'),
    ]

    operations = [
    ]
