# Generated by Django 5.0.2 on 2024-02-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0011_merge_20240225_0003'),
        ('techwave', '0014_merge_20240225_0410'),
    ]

    operations = [
    ]
