# Generated by Django 5.0.2 on 2024-02-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techwave', '0015_comments'),
        ('techwave', '0015_merge_20240226_1458'),
    ]

    operations = [
    ]
